### PR TITLE
Add zh-CN.qm & zh-CN.ts

### PR DESCRIPTION
**Pull request by Jerry23011**
Hi, I just got these done
Please feel free to do any editing for these files as I might have made mistakes since this is the first time working with Qt

### CODE REVIEW

**Comment by adriweb** [comment]
I added the few code modifications to take into account the new file, looks like it works fine :)
image

**Comment by Jerry23011** [comment]
Awesome! If anyone raises an issue on the translations, please don't hesitate to @ me so that I can get them fixed after discussing

**Comment by adriweb** [comment]
Can you take a look at #445 ? :)

**Comment by Jerry23011** [comment]
Reviewing

**Pull request merged**
