### PR TITLE
Add SmartPad support

### PR DESCRIPTION
**Pull request by TheLastMillennial**
Added new option to Key Bindings under the General Settings to select 'SmartPad'. This will allow a user to connect their calculator (running the SmartPad app) to their computer, and control the CEmu Keypad with it.

Testing needed on Windows:
Pressing a key that contains the combination Alt+Ctrl+Win+Shift on Windows 10 will launch the Office application (or a webpage asking you to download Office). I have already disabled this via a [Registry tweak](https://web.archive.org/web/20211125095040/https://www.tenforums.com/microsoft-office-365/154729-disable-shift-ctrl-windows-alt-opening-login-office.html) so I cannot test. I need to be sure this nuisance won't appear on other's machines.

### CODE REVIEW

**Review by jacobly0 — APPROVED** [review]
Works on linux (with `xkb_options srvrkeys:none`).

**Comment by adriweb** [comment]
So hm, on macOS, some keys  don't work, and most keys that work don't get released (in fact, only Enter seems to behave fine)

~~Keys that don't work: `2nd`, `mode`, `del`, arrows, `alpha`, `Xtn`, `stats`, `résol`, `,`, `(`, `)`~~
_actually nevermind it's rather random and most of the time it doesn't work as expected._

**Comment by TheLastMillennial** [comment]
[enter] is the only key that TI implemented sensibly into Smartpad. By default, [enter] on the calculator simply maps to [enter] on a keyboard. That's probably why it works reliably.

The rest of the keys utilize some combination of [meta] and the [ctrl], [alt], or [shift] keys.

Maybe the issue lies with global keyboard shortcuts? I read you can turn them off on Mac by doing:
1.     Open System Preferences
2.     Click Keyboard
3.     Click Shortcuts pill (third one from the left)
4.     Deselect all checked shortcuts

**Comment by TheLastMillennial** [comment]
I'm not sure what SV is? 
So, is this a problem that still needs to be addressed?

**Comment by TheLastMillennial** [comment]
This may not be the best solution, but I found a way to disable _all_ shortcuts: https://stackoverflow.com/questions/5311459/disable-keyboard-shortcut

**Comment by adriweb** [comment]
So hm, should we merge this addign a warning that it may only work correctly under some circumstances?

**Comment by adriweb** [comment]
How does it behave on Windows?

**Comment by TheLastMillennial** [comment]
It works totally fine unless the user has Microsoft Office installed. SmartPad will sometimes trigger the global shortcut (ctrl+alt+shift+win) to open the Office application.
You can disable this either by [installing software](https://github.com/acook/OfficeKeyFix) to disable all office shortcuts, or applying a [registry tweak](https://answers.microsoft.com/en-us/windows/forum/all/disabling-the-office-hotkey-in-windows-10/58e2f30f-8556-4f73-bf0c-56544697218d) to just disable the Office shortcut.

Perhaps this PR should look into disabling the Office shortcut while CEmu is open?

**Comment by adriweb** [comment]
Well, considering it has global conflicts on both Windows and macOS, maybe either:
- make the code available only on Linux
- Have a confirm popup warning of potential issues, before it gets actually enabled when the win/mac user tries to enable it.

**Comment by calc84maniac** [comment]
Looking at the code in this PR, it appears that the Office shortcut is only used with function keys, so it wouldn't be necessary to use the full OfficeKeyFix. The real question is whether the registry tweak applies instantly without needing to restart explorer.exe, in which case it might be a viable option.

**Comment by TheLastMillennial** [comment]
I just now retested this and the behavior seems to have changed. I believe Office no longer opens whenever ctrl+alt+shift+win+anykey is pressed. It only opens when a valid shortcut is pressed (i.e. ctrl+alt+shift+win+d for onedrive). I was unable to get Office to open anymore using SmartPad so I don't think this is any issue anymore on Windows.

**Comment by adriweb** [comment]
Probably depends on the Windows/office version then I guess. In any case,
still probably warrants a warning shown to the user.

**Comment by adriweb** [comment]
> warning shown to the user 

Can anyone take care of this before we release v2.0?

**Comment by adriweb** [comment]
Done via cc5c270b6c322662648b4c818f1a5a99a0f286dc + c8ab95810ba95ef1fc2e353f185ec88f99fb390f

**Pull request closed without merging**
